version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=file:./prisma/bookshelf.db
    command: ['npm', 'run', 'dev']
  db:
    image: nouchka/sqlite3
    container_name: sqlite-db
    environment:
      - SQLITE_DB_PATH=/prisma/bookshelf.db
    volumes:
      - ./prisma/bookshelf.db:/app/db.sqlite
    ports:
      - '8080:8080'
